---
driver:
  name: ec2 
  aws_ssh_key_id: KeyName 
  region: us-east-1
  security_group_ids: ["sg-062d57897780445eb"]
  inistance_type: t2.micro
  associate_public_ip: yes


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
transport:
  ssh-key: ./KeyName.pem
platforms:
  - name: ubuntu 16.04
    driver:
      image_id: ami-0565af6e282977273
    transport:
      username: ubuntu
  - name: Redhat
    driver: 
      image_id: ami-011b3ccf1bd6db744
    transport:
      username: ec2-user
suites:
  - name: default
    run_list:
      - recipe[clearinfo::default]
    verifier:
      inspec_tests:
      - test/integration/default
    attributes:
