---
driver:
  name: ec2
  aws_ssh_key_id:  KeyName
  region: us-east-1
  instance_type: t2.micro
  #image_id: ami-0565af6e282977273
  #image_id: ami-011b3ccf1bd6db744
  #security_group_ids: ["sg-06cee26a39c73d4f5"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #- name: ubuntu-16.04
  - name: redhat
    driver:
      image_id: ami-011b3ccf1bd6db744
    transport:
      username: ec2-user
  - name: ubuntu-16.04
    driver: 
      image_id: ami-0565af6e282977273
    transport:
      username: ubuntu
transport:
  ssh_key: C:\Users\Teja\Downloads\Compressed\chef-repo\cookbooks\apache1_cookbook\KeyName.pem
  #username: ec2-user
suites:
  - name: default
    run_list:
      - recipe[apache2::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
